In [1]:
import numpy as np

np.__version__

'1.14.2'

In [2]:
L = [True, "2", 3.0, 4]
[type(item) for item in L]

[bool, str, float, int]

In [3]:
# integer array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
# upcast
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
# multidimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.seed(0)
np.random.randint(10, size = 6)

array([5, 0, 3, 3, 7, 9])

In [9]:
y = np.random.randint(10, size=(3,4))
y

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x = np.random.randint(10, size=(3, 4, 5))
print("x ndim: ", x.ndim) 
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype:", x.dtype)

('x ndim: ', 3)
('x shape:', (3, 4, 5))
('x size: ', 60)
('x dtype:', dtype('int64'))


In [11]:
# reverse every other from index 5
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[5::-2]

array([5, 3, 1])

In [12]:
# all rows, every other column
y[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [13]:
# y sub copy
y[:2, :2].copy()


array([[3, 5],
       [7, 6]])

In [14]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# row vector via reshape
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [16]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [18]:
# concatenate along the second axis (zero-indexed)
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [21]:
x = np.array([1, 2, 3])
y = np.array([[99],
              [99]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
# horizontally stack the arrays
np.hstack([y, grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [23]:
grid = np.arange(16).reshape((4, 4))
grid


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
upper, lower = np.vsplit(grid, [2])
upper


array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
left, right = np.hsplit(grid, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [27]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])