In [1]:
import tensorflow as tf
from tensorflow import keras

tf.__version__


'1.13.1'

In [2]:
keras.__version__


'2.2.4-tf'

In [3]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()


In [4]:
X_train_full.shape


(60000, 28, 28)

In [5]:
X_train_full.dtype


dtype('uint8')

In [6]:
X_valid, X_train = X_train_full[:5000]/255.0, X_train_full[5000:]/255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]


In [7]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]
class_names[y_train[0]]


'Coat'

In [8]:
from keras.models import Sequential

model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

model.summary()


Instructions for updating:
Colocations handled automatically by placer.


Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

history = model.fit(X_train, y_train, epochs=10, validation_data=(X_valid, y_valid))


Train on 55000 samples, validate on 5000 samples
Epoch 1/10
55000/55000 [==============================] - 13s 238us/sample - loss: 0.7190 - acc: 0.7621 - val_loss: 0.5071 - val_acc: 0.8324
Epoch 2/10
55000/55000 [==============================] - 13s 233us/sample - loss: 0.4915 - acc: 0.8267 - val_loss: 0.4455 - val_acc: 0.8486
Epoch 3/10
55000/55000 [==============================] - 12s 217us/sample - loss: 0.4467 - acc: 0.8427 - val_loss: 0.4233 - val_acc: 0.8544
Epoch 4/10
55000/55000 [==============================] - 12s 210us/sample - loss: 0.4205 - acc: 0.8520 - val_loss: 0.4039 - val_acc: 0.8604
Epoch 5/10
55000/55000 [==============================] - 11s 208us/sample - loss: 0.4006 - acc: 0.8579 - val_loss: 0.4100 - val_acc: 0.8522
Epoch 6/10
55000/55000 [==============================] - 12s 216us/sample - loss: 0.3843 - acc: 0.8639 - val_loss: 0.3754 - val_acc: 0.8712
Epoch 7/10
55000/55000 [==============================] - 11s 209us/sample - loss: 0.3719 - acc: 0.8679 -

In [10]:
# import pandas as pd

# pd.DataFrame(history.history).plot(figsize=(8,5))
# plt.grid(True)
# plt.gca().set_ylim(0, 1)
# plt.show()


In [11]:
model.evaluate(X_test, y_test)


10000/10000 [==============================] - 1s 81us/sample - loss: 2.5581 - acc: 0.8381


[2.5581236440658555, 0.8381]

In [12]:
X_new = X_test[:3]
y_proba = model.predict(X_new)
y_proba.round(2)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [13]:
y_pred = model.predict_classes(X_new)
y_pred


array([9, 2, 1])

In [14]:
import numpy as np

np.array(class_names)[y_pred]


array(['Ankle boot', 'Pullover', 'Trouser'], dtype='<U11')

In [15]:
y_new = y_test[:3]
y_new

array([9, 2, 1], dtype=uint8)